### ISSUE TITLE
Feature: Multiple Surfaces for ball rolling

### ISSUE THREAD

**Issue by MysticalLatios** [MysticalLatios/Animal-Ball-Maker#1]

**Comment by MysticalLatios** [comment]
Ideas:
Bouncy surface,
Slippery surface,
Slow/Gripy surface.

**Comment by RosyMapleMoth** [comment]
with commit a8ea1bbf32c8e4c8ee941a0e3515931fedab57ef, 

added
physics materials, and materials.
+ Basic : baseline block low bounce, around .6 friction
+ Grass : green, high dynamic low static friction.
+ Bouncy : pink, high boncieness.
+ Ice : no friction(consider refactor) .
+ Glue : no bounce, high dynamic high static friction.

also added a basic prefab with variants allowing for testing when we have tilting map.

**Comment by MysticalLatios** [comment]
Nice job, closing for completion.
