### ISSUE TITLE
Tool : map tilt controls from keyboard

### ISSUE THREAD

**Issue by RosyMapleMoth** [MysticalLatios/Animal-Ball-Maker#8]
Create a script to allow wasd or arrow key tilt controls for easier game testing without gyro. 

issue is complete when 
- [x] wasd or arrow key input is converted to rotation for an object 
- [x] ~~The level tilts around the center some fixed point (this is not ideal for the end production but is fine for testing)~~ this is no longer used
- [x] level tilts around the player's position.
- [x] the script can be relatively easily added to any level, for testing.

**Comment by MysticalLatios** [comment]
For testing this should be a priority

**Comment by RosyMapleMoth** [comment]
with commit 268222c2305b11a61f32751d3feae53c8c415897 

adds 
+ arrow key rotation of an object about a point(this point is the point of rotation of the game object with the script attached)
+ using an empty object with all prefabs we want to rotate as children we can now rotate a map about a single point, with relative ease.
